import { createActions } from 'redux-actions';
import {
    GET_PLAN,
    GET_PLAN_ERROR,
    SET_PLAN,
    SET_PLAN_ERROR,
    BIND_PLAN,
    PATCH_PLAN,
    PATCH_PLAN_ERROR,
    PATCH_PLAN_CASHFLOW,
    BIND_PLAN_ERROR,
    CREATE_PLAN,
    CREATE_PLAN_ERROR,
    ADD_PLAN_ASSET,
    ADD_PLAN_ASSET_ERROR,
    UPDATE_PLAN_ASSET,
    UPDATE_PLAN_ASSET_ERROR,
    ADD_PLAN_CASHFLOW,
    ADD_PLAN_CASHFLOW_ERROR,
    ADD_PLAN_DEBT,
    ADD_PLAN_DEBT_ERROR,
    UPDATE_PLAN_DEBT,
    UPDATE_PLAN_DEBT_ERROR,
    ADD_PLAN_DEBT_CASHFLOW,
    ADD_PLAN_DEBT_CASHFLOW_ERROR,
    ADD_PLAN_JOB,
    ADD_PLAN_JOB_ERROR,
    UPDATE_PLAN_JOB,
    UPDATE_PLAN_JOB_ERROR,
    ADD_PLAN_JOB_CASHFLOW,
    ADD_PLAN_JOB_CASHFLOW_ERROR,
    UPDATE_PLAN_CASHFLOW,
    UPDATE_PLAN_CASHFLOW_ERROR,
    ADD_PLAN_ADDRESS,
    ADD_USER_ADDRESS,
    ADD_PLAN_ADDRESS_ERROR,
    ADD_PLAN_ADDRESS_PROPERTY,
    UPDATE_PLAN_ADDRESS,
    UPDATE_USER_ADDRESS,
    UPDATE_PLAN_ADDRESS_ERROR,
    REMOVE_PLAN_ADDRESS,
    REMOVE_PLAN_ADDRESS_ERROR,
    ADD_PLAN_GIVING,
    ADD_PLAN_GIVING_ERROR,
    UPDATE_PLAN_GIVING,
    UPDATE_PLAN_GIVING_ERROR,
    ADD_PLAN_GIVING_CASHFLOW,
    ADD_PLAN_GIVING_CASHFLOW_ERROR,
    CREATE_PLAN_USER,
    CREATE_PLAN_USER_ERROR,
    UPDATE_PLAN_USER,
    UPDATE_PLAN_USER_ERROR,
    ADD_PARTNER_ADDRESS,
    UPDATE_PARTNER_ADDRESS,
    SET_MAIN_USER_ADDRESS_TO_PARTNER,
    ADD_CASHFLOW_TO_JOB,
    ADD_CASHFLOW_TO_ASSET,
    ADD_CASHFLOW,
    ADD_USER_POSTAL_ADDRESS,
    CREATE_SOFT_FACTS,
    CREATE_SOFT_FACTS_ERROR,
    GET_SOFT_FACTS,
    GET_SOFT_FACTS_ERROR,
    GET_SINGLE_SOFT_FACTS,
    GET_SINGLE_SOFT_FACTS_ERROR,
    DELETE_SOFT_FACTS,
    DELETE_SOFT_FACTS_ERROR,
    UPDATE_INCOME_CHANGES,
    ADD_DEPENDENTS_CASHFLOW,
    UPDATE_CASHFLOW,
    SUBMIT_PLAN,
    UPLOAD_IMAGE,
} from './types/PlanTypes';

export const {
    getPlan,
    getPlanError,
    setPlan,
    setPlanError,
    bindPlan,
    bindPlanError,
    patchPlan,
    patchPlanCashflow,
    patchPlanError,
    createPlan,
    createPlanError,
    addPlanAsset,
    addPlanAssetError,
    updatePlanAsset,
    updatePlanAssetError,
    addPlanCashflow,
    addPlanCashflowError,
    addPlanDebt,
    addPlanDebtError,
    updatePlanDebt,
    updatePlanDebtError,
    addPlanDebtCashflow,
    addPlanDebtCashflowError,
    addPlanJob,
    addPlanJobError,
    updatePlanJob,
    updatePlanJobError,
    addPlanJobCashflow,
    addPlanJobCashflowError,
    updatePlanCashflow,
    updatePlanCashflowError,
    addPlanAddress,
    addUserAddress,
    addPlanAddressProperty,
    addPlanAddressError,
    updatePlanAddress,
    updatePlanAddressError,
    removePlanAddress,
    removePlanAddressError,
    addPlanGiving,
    addPlanGivingError,
    updatePlanGiving,
    updatePlanGivingError,
    addPlanGivingCashflow,
    addPlanGivingCashflowError,
    createPlanUser,
    createPlanUserError,
    updatePlanUser,
    updatePlanUserError,
    addPartnerAddress,
    updatePartnerAddress,
    setMainUserAddressToPartner,
    addCashflowToJob,
    addCashflowToAsset,
    addCashflow,
    addUserPostalAddress,
    createSoftFacts,
    createSoftFactsError,
    getSoftFacts,
    getSoftFactsError,
    getSingleSoftFacts,
    getSingleSoftFactsError,
    deleteSoftFacts,
    deleteSoftFactsError,
    updateIncomeChanges,
    addDependentsCashflow,
    updateCashflow,
    submitPlan,
} = createActions({
    // Creating plan
    [CREATE_PLAN]: payload => payload,
    [CREATE_PLAN_ERROR]: payload => payload,
    // Binding plan
    [BIND_PLAN]: payload => payload,
    [BIND_PLAN_ERROR]: payload => payload,
    // Getting plan
    [GET_PLAN]: payload => payload,
    [GET_PLAN_ERROR]: payload => payload,
    // Setting plan
    [SET_PLAN]: payload => payload,
    [SET_PLAN_ERROR]: payload => payload,
    // Patching plan
    [PATCH_PLAN]: payload => payload,
    [PATCH_PLAN_ERROR]: payload => payload,
    [PATCH_PLAN_CASHFLOW]: payload => payload,
    // Adding plan asset
    [ADD_PLAN_ASSET]: payload => payload,
    [ADD_PLAN_ASSET_ERROR]: payload => payload,
    // Updating plan asset
    [UPDATE_PLAN_ASSET]: payload => payload,
    [UPDATE_PLAN_ASSET_ERROR]: payload => payload,
    // Adding plan cashflow
    [ADD_PLAN_CASHFLOW]: payload => payload,
    [ADD_PLAN_CASHFLOW_ERROR]: payload => payload,
    // Adding plan debt
    [ADD_PLAN_DEBT]: payload => payload,
    [ADD_PLAN_DEBT_ERROR]: payload => payload,
    // Updating plan debt
    [UPDATE_PLAN_DEBT]: payload => payload,
    [UPDATE_PLAN_DEBT_ERROR]: payload => payload,
    // Adding plan debt cashflow
    [ADD_PLAN_DEBT_CASHFLOW]: payload => payload,
    [ADD_PLAN_DEBT_CASHFLOW_ERROR]: payload => payload,
    // Adding plan job
    [ADD_PLAN_JOB]: payload => payload,
    [ADD_PLAN_JOB_ERROR]: payload => payload,
    // Updating plan job
    [UPDATE_PLAN_JOB]: payload => payload,
    [UPDATE_PLAN_JOB_ERROR]: payload => payload,
    // Adding plan job cashflow
    [ADD_PLAN_JOB_CASHFLOW]: payload => payload,
    [ADD_PLAN_JOB_CASHFLOW_ERROR]: payload => payload,
    // Updating plan cashflow
    [UPDATE_PLAN_CASHFLOW]: payload => payload,
    [UPDATE_PLAN_CASHFLOW_ERROR]: payload => payload,
    // Adding plan address
    [ADD_PLAN_ADDRESS]: payload => payload,
    [ADD_USER_ADDRESS]: payload => payload,
    [ADD_PLAN_ADDRESS_ERROR]: payload => payload,
    [ADD_PLAN_ADDRESS_PROPERTY]: payload => payload,
    // Updating plan address
    [UPDATE_PLAN_ADDRESS]: payload => payload,
    [UPDATE_USER_ADDRESS]: payload => payload,
    [UPDATE_PLAN_ADDRESS_ERROR]: payload => payload,
    // Removing plan address
    [REMOVE_PLAN_ADDRESS]: payload => payload,
    [REMOVE_PLAN_ADDRESS_ERROR]: payload => payload,
    // Adding plan giving
    [ADD_PLAN_GIVING]: payload => payload,
    [ADD_PLAN_GIVING_ERROR]: payload => payload,
    // Updating plan giving
    [UPDATE_PLAN_GIVING]: payload => payload,
    [UPDATE_PLAN_GIVING_ERROR]: payload => payload,
    // Adding plan giving cashflow
    [ADD_PLAN_GIVING_CASHFLOW]: payload => payload,
    [ADD_PLAN_GIVING_CASHFLOW_ERROR]: payload => payload,
    // Creating plan user
    [CREATE_PLAN_USER]: payload => payload,
    [CREATE_PLAN_USER_ERROR]: payload => payload,
    // Updating plan user
    [UPDATE_PLAN_USER]: payload => payload,
    [UPDATE_PLAN_USER_ERROR]: payload => payload,
    // Partner address setting / updating / getting from main user
    [ADD_PARTNER_ADDRESS]: payload => payload,
    [UPDATE_PARTNER_ADDRESS]: payload => payload,
    [SET_MAIN_USER_ADDRESS_TO_PARTNER]: payload => payload,
    [ADD_CASHFLOW_TO_JOB]: payload => payload,
    [ADD_CASHFLOW_TO_ASSET]: payload => payload,
    [ADD_CASHFLOW]: payload => payload,
    // Adding postal address to user
    [ADD_USER_POSTAL_ADDRESS]: payload => payload,
    // Soft Facts
    [CREATE_SOFT_FACTS]: payload => payload,
    [CREATE_SOFT_FACTS_ERROR]: payload => payload,
    [GET_SOFT_FACTS]: payload => payload,
    [GET_SOFT_FACTS_ERROR]: payload => payload,
    [GET_SINGLE_SOFT_FACTS]: payload => payload,
    [GET_SINGLE_SOFT_FACTS_ERROR]: payload => payload,
    [DELETE_SOFT_FACTS]: payload => payload,
    [DELETE_SOFT_FACTS_ERROR]: payload => payload,
    // Other Incomes
    [UPDATE_INCOME_CHANGES]: payload => payload,
    // Adding cashflow to dependents
    [ADD_DEPENDENTS_CASHFLOW]: payload => payload,
    // Updating cashflow
    [UPDATE_CASHFLOW]: payload => payload,
    // Submit Plan
    [SUBMIT_PLAN]: payload => payload,
    [UPLOAD_IMAGE]: payload => payload,
});
