/**
 * Address actions
 *
 */

// Searching address
export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';
export const SEARCH_ADDRESS_ERROR = 'SEARCH_ADDRESS_ERROR';

// Getting address list
export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST';
export const GET_ADDRESS_LIST_ERROR = 'GET_ADDRESS_LIST_ERROR';
export const RESET_ADDRESS_LIST = 'RESET_ADDRESS_LIST';
export const GET_POSTAL_ADDRESS_LIST = 'GET_POSTAL_ADDRESS_LIST';
export const GET_POSTAL_ADDRESS_LIST_ERROR = 'GET_POSTAL_ADDRESS_LIST_ERROR';

// Setting address list
export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST';
export const SET_ADDRESS_LIST_ERROR = 'SET_ADDRESS_LIST_ERROR';
export const SET_POSTAL_ADDRESS_LIST = 'SET_POSTAL_ADDRESS_LIST';
export const SET_POSTAL_ADDRESS_LIST_ERROR = 'SET_POSTAL_ADDRESS_LIST_ERROR';
