/**
 * Plan actions
 *
 */

// Creating plan
export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_ERROR = 'CREATE_PLAN_ERROR';

// Binding plan
export const BIND_PLAN = 'BIND_PLAN';
export const BIND_PLAN_ERROR = 'BIND_PLAN_ERROR';

// Getting plan
export const GET_PLAN = 'GET_PLAN';
export const GET_PLAN_ERROR = 'GET_PLAN_ERROR';

// Setting plan
export const SET_PLAN = 'SET_PLAN';
export const SET_PLAN_ERROR = 'SET_PLAN_ERROR';

// Patching plan
export const PATCH_PLAN = 'PATCH_PLAN';
export const PATCH_PLAN_ERROR = 'PATCH_PLAN_ERROR';

// Plan assets
export const ADD_PLAN_ASSET = 'ADD_PLAN_ASSET';
export const ADD_PLAN_ASSET_ERROR = 'ADD_PLAN_ASSET_ERROR';
export const UPDATE_PLAN_ASSET = 'UPDATE_PLAN_ASSET';
export const UPDATE_PLAN_ASSET_ERROR = 'UPDATE_PLAN_ASSET_ERROR';
export const ADD_PLAN_ADDRESS_PROPERTY = 'ADD_PLAN_ADDRESS_PROPERTY';

// Plan cashflow
export const ADD_CASHFLOW = 'ADD_CASHFLOW';
export const ADD_PLAN_CASHFLOW = 'ADD_PLAN_CASHFLOW';
export const ADD_PLAN_CASHFLOW_ERROR = 'ADD_PLAN_CASHFLOW_ERROR';
export const ADD_DEPENDENTS_CASHFLOW = 'ADD_DEPENDENTS_CASHFLOW';
export const UPDATE_PLAN_CASHFLOW = 'UPDATE_PLAN_CASHFLOW';
export const UPDATE_CASHFLOW = 'UPDATE_CASHFLOW';
export const UPDATE_PLAN_CASHFLOW_ERROR = 'UPDATE_PLAN_CASHFLOW_ERROR';
export const ADD_CASHFLOW_TO_JOB = 'ADD_CASHFLOW_TO_JOB';
export const ADD_CASHFLOW_TO_ASSET = 'ADD_CASHFLOW_TO_ASSET';
export const PATCH_PLAN_CASHFLOW = 'PATCH_PLAN_CASHFLOW';

// Plan debt
export const ADD_PLAN_DEBT = 'ADD_PLAN_DEBT';
export const ADD_PLAN_DEBT_ERROR = 'ADD_PLAN_DEBT_ERROR';
export const UPDATE_PLAN_DEBT = 'UPDATE_PLAN_DEBT';
export const UPDATE_PLAN_DEBT_ERROR = 'UPDATE_PLAN_DEBT_ERROR';
export const ADD_PLAN_DEBT_CASHFLOW = 'ADD_PLAN_DEBT_CASHFLOW';
export const ADD_PLAN_DEBT_CASHFLOW_ERROR = 'ADD_PLAN_DEBT_CASHFLOW_ERROR';

// Plan job
export const ADD_PLAN_JOB = 'ADD_PLAN_JOB';
export const ADD_PLAN_JOB_ERROR = 'ADD_PLAN_JOB_ERROR';
export const UPDATE_PLAN_JOB = 'UPDATE_PLAN_JOB';
export const UPDATE_PLAN_JOB_ERROR = 'UPDATE_PLAN_JOB_ERROR';
export const ADD_PLAN_JOB_CASHFLOW = 'ADD_PLAN_JOB_CASHFLOW';
export const ADD_PLAN_JOB_CASHFLOW_ERROR = 'ADD_PLAN_JOB_CASHFLOW_ERROR';

// Plan address
export const ADD_PLAN_ADDRESS = 'ADD_PLAN_ADDRESS';
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const ADD_USER_POSTAL_ADDRESS = 'ADD_USER_POSTAL_ADDRESS';
export const ADD_PLAN_ADDRESS_ERROR = 'ADD_PLAN_ADDRESS_ERROR';
export const UPDATE_PLAN_ADDRESS = 'UPDATE_PLAN_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_PLAN_ADDRESS';
export const UPDATE_PLAN_ADDRESS_ERROR = 'UPDATE_PLAN_ADDRESS_ERROR';
export const REMOVE_PLAN_ADDRESS = 'REMOVE_PLAN_ADDRESS';
export const REMOVE_PLAN_ADDRESS_ERROR = 'REMOVE_PLAN_ADDRESS_ERROR';

export const ADD_PARTNER_ADDRESS = 'ADD_PARTNER_ADDRESS';
export const UPDATE_PARTNER_ADDRESS = 'UPDATE_PARTNER_ADDRESS';
export const SET_MAIN_USER_ADDRESS_TO_PARTNER = 'SET_MAIN_USER_ADDRESS_TO_PARTNER';

// Plan giving
export const ADD_PLAN_GIVING = 'ADD_PLAN_GIVING';
export const ADD_PLAN_GIVING_ERROR = 'ADD_PLAN_GIVING_ERROR';
export const UPDATE_PLAN_GIVING = 'UPDATE_PLAN_GIVING';
export const UPDATE_PLAN_GIVING_ERROR = 'UPDATE_PLAN_GIVING_ERROR';
export const ADD_PLAN_GIVING_CASHFLOW = 'ADD_PLAN_GIVING_CASHFLOW';
export const ADD_PLAN_GIVING_CASHFLOW_ERROR = 'ADD_PLAN_GIVING_CASHFLOW_ERROR';
export const UPDATE_INCOME_CHANGES = 'UPDATE_INCOME_CHANGES';
// Creating plan user
export const CREATE_PLAN_USER = 'CREATE_PLAN_USER';
export const CREATE_PLAN_USER_ERROR = 'CREATE_PLAN_USER_ERROR';
export const UPDATE_PLAN_USER = 'UPDATE_PLAN_USER';
export const UPDATE_PLAN_USER_ERROR = 'UPDATE_PLAN_USER_ERROR';


// Soft facts
export const CREATE_SOFT_FACTS = 'CREATE_SOFT_FACTS';
export const CREATE_SOFT_FACTS_ERROR = 'CREATE_SOFT_FACTS_ERROR';
export const GET_SOFT_FACTS = 'GET_SOFT_FACTS';
export const GET_SOFT_FACTS_ERROR = 'GET_SOFT_FACTS_ERROR';
export const GET_SINGLE_SOFT_FACTS = 'GET_SINGLE_SOFT_FACTS';
export const GET_SINGLE_SOFT_FACTS_ERROR = 'GET_SINGLE_SOFT_FACTS_ERROR';
export const DELETE_SOFT_FACTS = 'DELETE_SOFT_FACTS';
export const DELETE_SOFT_FACTS_ERROR = 'DELETE_SOFT_FACTS_ERROR';
export const SET_SOFT_FACTS = 'SET_SOFT_FACTS';

// Income Changes

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

export const SUBMIT_PLAN = 'SUBMIT_PLAN';
